export { default as MenuIcon } from "../../../public/icons/menu.svg";
export { default as CloseIcon } from "../../../public/icons/close.svg";
export { default as EmailIcon } from "../../../public/icons/email.svg";
export { default as PhoneIcon } from "../../../public/icons/phone.svg";
export { default as SecondPhoneIcon } from "../../../public/icons/phone1.svg";
export { default as SecondEmail } from "../../../public/icons/mail1.svg";
export { default as Linkdln } from "../../../public/icons/linkedin.svg";
export { default as Youtube } from "../../../public/icons/youtube.svg";
export { default as Star } from "../../../public/icons/star.svg";
