import { Linkdln, SecondEmail, SecondPhoneIcon, Youtube } from "@/assets/icons";
import { Job } from "@/components/jobs/JobListItem";

export const Menu = [
  {
    title: "HOME",
    url: "/",
  },
  {
    title: "ABOUT ME",
    url: "/about-me",
  },

  {
    title: "JOBS",
    url: "/jobs",
  },
  {
    title: "CLIENTS",
    url: "/clients",
  },
  {
    title: "CONTACT",
    url: "/contact",
  },
];

export enum BreakPoints {
  MOBILE = 640,
  TABLET = 768,
  LAPTOP = 1024,
}

export const EMAIL = "shaun@arkhamtalent.com";
export const PHONE = "(516) 852-4011";

export const Contacts = [
  {
    icon: SecondEmail,
    type: "email",
    link: EMAIL,
    newTab: false,
    scheme: "mailto:",
  },
  {
    icon: SecondPhoneIcon,
    type: "phone",
    link: `${PHONE}`,
    scheme: "tel:",
    newTab: false,
  },
];

export const Socials = [
  {
    icon: Linkdln,
    type: "social",
    link: "https://www.linkedin.com/company/arkhamtalent/",
    newTab: true,
  },
  {
    icon: Youtube,
    type: "social",
    link: "https://www.youtube.com/@ArkhamTalent",
    newTab: true,
  },
];

export const FAKEDATA: Job[] = [
  {
    title: "Customer Service Analyst",
    short_desc:
      "Job Description The opportunityThis role is accountable for providing quality, phone based customer service to callers. Requires advanced knowledge of products and processes to res...",
    slug: "customer-service-analyst-1",
    long_desc: `<p dir="ltr">
                  <!---->The opportunity<!----><span><br></span><span><br></span><!---->We are looking for Project Manager who is able to manages, coordinates business and technical projects through all phases of professional project manager: initiation, Planning, Executing, Monitor &amp; Control and Close. You shall work with dynamic, professional, and strong core values organization.<!----><span><br></span><span><br></span><span><strong><!---->Responsibilities<!----><span><br></span><span><br></span></strong></span><span>      <ul><span><li><!---->Responsible for Planning, Executing, Monitor &amp; Control and Close technical and business projects across multiple stakeholders; developing analysis to support process and project improvements.<!----></li></span><span><li><!---->Manages and coordinates business and technical projects through all phases of initiation, development, and implementation; tends to work on waterfall projects<!----></li></span><span><li><!---->Works with business to define and manage the scope, strategy, requirements, and implementation of projects<!----></li></span><span><li><!---->Ensures that assigned projects are completed within budgets and schedules while meeting business objectives<!----></li></span><span><li><!---->Identifies, analyzes, mitigates, documents, and controls project risks<!----></li></span><span><li><!---->Provides effective and regular communication within the project team, stakeholders, sponsors, and management<!----></li></span><span><li><!---->Identifies resource needs for the project and establishes roles, expectations, and goals with team members<!----></li></span><span><li><!---->Assess and manages risks that impede successful project delivery<!----></li></span><span><li><!---->Has positive impact to specific organizational entities &amp; has some understanding of the nature of the impact<!----></li></span><span><li><!---->Participates in negotiation of contract terms and conditions and ensure compliance with contract terms for project consultants and vendors<!----></li></span><span><li><!---->Responsible for assisting in hiring project staff, and developing motivating, coaching, advising, and managing the project team<!----></li></span><span><li><!---->Manage the technical components of the project or act as manager of personnel, including evaluating personnel<!----><span><br></span><span><br></span></li></span></ul>
</span><span><strong><!---->How will you create impact?<!----><span><br></span><span><br></span></strong></span><!---->This role report to Head of IT Delivery. You are IT delivery manager to delivery technology roadmap of organization to business. Working very closely with Business to understand demand and consult, drive them for digital transformation<!----><span><br></span><span><br></span><span><strong><!---->What motivates you?<!----><span><br></span><span><br></span></strong></span><span>      <ul><span><li><!---->You obsess about customers, listen, engage, and act for their benefit.<!----></li></span><span><li><!---->You think big, with curiosity to discover ways to use your agile approach and enable business outcomes.<!----></li></span><span><li><!---->You thrive in teams and enjoy getting things done together.<!----></li></span><span><li><!---->You take ownership and build solutions, focusing on what matters.<!----></li></span><span><li><!---->You do what is right, work with integrity and speak up.<!----></li></span><span><li><!---->You share your humanity, helping us build a diverse and inclusive work environment for everyone.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->What we are looking for<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->Proven Experienced and strong project management experience using waterfall and agile.<!----></li></span><span><li><!---->Well planning, execute, Monitor and control project scope, budget, time.<!----></li></span><span><li><!---->Excellent stakeholder’s management and communication<!----></li></span><span><li><!---->Life insurance industry experience is plus<!----></li></span><span><li><!---->Experience working with distributed teams across locations.<!----></li></span><span><li><!---->Good at communication skills, both in English and Vietnamese<!----></li></span><span><li><!---->Good problem solving<!----></li></span><span><li><!---->Certified PMI-PMP is preferable.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->What can we offer you?<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->A competitive salary and benefits packages.<!----></li></span><span><li><!---->A growth trajectory that extends upward and outward, encouraging you to follow your passions and learn new skills.<!----></li></span><span><li><!---->A focus on growing your career path with us.<!----></li></span><span><li><!---->Flexible work policies and strong work-life balance.<!----></li></span><span><li><!---->Professional development and leadership opportunities.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->Our commitment to you<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->Values-first culture: We lead with our Values every day and bring them to life together.<!----></li></span><span><li><!---->Boundless opportunity: We create opportunities to learn and grow at every stage of your career.<!----></li></span><span><li><!---->Continuous innovation: We invite you to help redefine the future of financial services.<!----></li></span><span><li><!---->Delivering the promise of Diversity, Equity and Inclusion: We foster an inclusive workplace where everyone thrives.<!----></li></span><span><li><!---->Championing Corporate Citizenship: We build a business that benefits all stakeholders and has a positive social and environmental impact.<!----><span><br></span><span><br></span></li></span></ul>
</span><span><strong><!---->About Manulife And John Hancock<!----><span><br></span><span><br></span></strong></span><!---->Manulife Financial Corporation is a leading international financial services provider, helping people make their decisions easier and lives better. To learn more about us, visit<span class="white-space-pre"> </span><a class="app-aware-link " target="_blank" href="https://www.manulife.com/en/about/our-story.html" data-test-app-aware-link=""><!---->https://www.manulife.com/en/about/our-story.html<!----></a><!---->.<!----><span><br></span><span><br></span><span><strong><!---->Manulife is an Equal Opportunity Employer<!----><span><br></span><span><br></span></strong></span><!---->At Manulife/John Hancock, we embrace our diversity. We strive to attract, develop and retain a workforce that is as diverse as the customers we serve and to foster an inclusive work environment that embraces the strength of cultures and individuals. We are committed to fair recruitment, retention, advancement and compensation, and we administer all of our practices and programs without discrimination on the basis of race, ancestry, place of origin, colour, ethnic origin, citizenship, religion or religious beliefs, creed, sex (including pregnancy and pregnancy-related conditions), sexual orientation, genetic characteristics, veteran status, gender identity, gender expression, age, marital status, family status, disability, or any other ground protected by applicable law.<!----><span><br></span><span><br></span><!---->It is our priority to remove barriers to provide equal access to employment. A Human Resources representative will work with applicants who request a reasonable accommodation during the application process. All information shared during the accommodation request process will be stored and used in a manner that is consistent with applicable laws and Manulife/John Hancock policies. To request a reasonable accommodation in the application process, contact recruitment@manulife.com.<!----><span><br></span><span><br></span><span><strong><!---->Working Arrangement<!----><span><br></span><span><br></span></strong></span><!---->Hybrid<!---->
                </p>`,
    salary: "700$",
    company: "Manulife",
    location: "NewYork, USA",
    company_logo:
      "https://cdn-dynamic.talent.com/ajax/img/get-logo.php?empcode=manulife&empname=Manulife&v=024",
  },
  {
    title: "Customer Service Analyst 2",
    short_desc:
      "Job Description The opportunityThis role is accountable for providing quality, phone based customer service to callers. Requires advanced knowledge of products and processes to res...",
    company: "Manulife",
    slug: "customer-service-analyst-2",
    salary: "700$",
    long_desc: `<p dir="ltr">
    <!---->The opportunity<!----><span><br></span><span><br></span><!---->We are looking for Project Manager who is able to manages, coordinates business and technical projects through all phases of professional project manager: initiation, Planning, Executing, Monitor &amp; Control and Close. You shall work with dynamic, professional, and strong core values organization.<!----><span><br></span><span><br></span><span><strong><!---->Responsibilities<!----><span><br></span><span><br></span></strong></span><span>      <ul><span><li><!---->Responsible for Planning, Executing, Monitor &amp; Control and Close technical and business projects across multiple stakeholders; developing analysis to support process and project improvements.<!----></li></span><span><li><!---->Manages and coordinates business and technical projects through all phases of initiation, development, and implementation; tends to work on waterfall projects<!----></li></span><span><li><!---->Works with business to define and manage the scope, strategy, requirements, and implementation of projects<!----></li></span><span><li><!---->Ensures that assigned projects are completed within budgets and schedules while meeting business objectives<!----></li></span><span><li><!---->Identifies, analyzes, mitigates, documents, and controls project risks<!----></li></span><span><li><!---->Provides effective and regular communication within the project team, stakeholders, sponsors, and management<!----></li></span><span><li><!---->Identifies resource needs for the project and establishes roles, expectations, and goals with team members<!----></li></span><span><li><!---->Assess and manages risks that impede successful project delivery<!----></li></span><span><li><!---->Has positive impact to specific organizational entities &amp; has some understanding of the nature of the impact<!----></li></span><span><li><!---->Participates in negotiation of contract terms and conditions and ensure compliance with contract terms for project consultants and vendors<!----></li></span><span><li><!---->Responsible for assisting in hiring project staff, and developing motivating, coaching, advising, and managing the project team<!----></li></span><span><li><!---->Manage the technical components of the project or act as manager of personnel, including evaluating personnel<!----><span><br></span><span><br></span></li></span></ul>
</span><span><strong><!---->How will you create impact?<!----><span><br></span><span><br></span></strong></span><!---->This role report to Head of IT Delivery. You are IT delivery manager to delivery technology roadmap of organization to business. Working very closely with Business to understand demand and consult, drive them for digital transformation<!----><span><br></span><span><br></span><span><strong><!---->What motivates you?<!----><span><br></span><span><br></span></strong></span><span>      <ul><span><li><!---->You obsess about customers, listen, engage, and act for their benefit.<!----></li></span><span><li><!---->You think big, with curiosity to discover ways to use your agile approach and enable business outcomes.<!----></li></span><span><li><!---->You thrive in teams and enjoy getting things done together.<!----></li></span><span><li><!---->You take ownership and build solutions, focusing on what matters.<!----></li></span><span><li><!---->You do what is right, work with integrity and speak up.<!----></li></span><span><li><!---->You share your humanity, helping us build a diverse and inclusive work environment for everyone.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->What we are looking for<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->Proven Experienced and strong project management experience using waterfall and agile.<!----></li></span><span><li><!---->Well planning, execute, Monitor and control project scope, budget, time.<!----></li></span><span><li><!---->Excellent stakeholder’s management and communication<!----></li></span><span><li><!---->Life insurance industry experience is plus<!----></li></span><span><li><!---->Experience working with distributed teams across locations.<!----></li></span><span><li><!---->Good at communication skills, both in English and Vietnamese<!----></li></span><span><li><!---->Good problem solving<!----></li></span><span><li><!---->Certified PMI-PMP is preferable.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->What can we offer you?<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->A competitive salary and benefits packages.<!----></li></span><span><li><!---->A growth trajectory that extends upward and outward, encouraging you to follow your passions and learn new skills.<!----></li></span><span><li><!---->A focus on growing your career path with us.<!----></li></span><span><li><!---->Flexible work policies and strong work-life balance.<!----></li></span><span><li><!---->Professional development and leadership opportunities.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->Our commitment to you<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->Values-first culture: We lead with our Values every day and bring them to life together.<!----></li></span><span><li><!---->Boundless opportunity: We create opportunities to learn and grow at every stage of your career.<!----></li></span><span><li><!---->Continuous innovation: We invite you to help redefine the future of financial services.<!----></li></span><span><li><!---->Delivering the promise of Diversity, Equity and Inclusion: We foster an inclusive workplace where everyone thrives.<!----></li></span><span><li><!---->Championing Corporate Citizenship: We build a business that benefits all stakeholders and has a positive social and environmental impact.<!----><span><br></span><span><br></span></li></span></ul>
</span><span><strong><!---->About Manulife And John Hancock<!----><span><br></span><span><br></span></strong></span><!---->Manulife Financial Corporation is a leading international financial services provider, helping people make their decisions easier and lives better. To learn more about us, visit<span class="white-space-pre"> </span><a class="app-aware-link " target="_blank" href="https://www.manulife.com/en/about/our-story.html" data-test-app-aware-link=""><!---->https://www.manulife.com/en/about/our-story.html<!----></a><!---->.<!----><span><br></span><span><br></span><span><strong><!---->Manulife is an Equal Opportunity Employer<!----><span><br></span><span><br></span></strong></span><!---->At Manulife/John Hancock, we embrace our diversity. We strive to attract, develop and retain a workforce that is as diverse as the customers we serve and to foster an inclusive work environment that embraces the strength of cultures and individuals. We are committed to fair recruitment, retention, advancement and compensation, and we administer all of our practices and programs without discrimination on the basis of race, ancestry, place of origin, colour, ethnic origin, citizenship, religion or religious beliefs, creed, sex (including pregnancy and pregnancy-related conditions), sexual orientation, genetic characteristics, veteran status, gender identity, gender expression, age, marital status, family status, disability, or any other ground protected by applicable law.<!----><span><br></span><span><br></span><!---->It is our priority to remove barriers to provide equal access to employment. A Human Resources representative will work with applicants who request a reasonable accommodation during the application process. All information shared during the accommodation request process will be stored and used in a manner that is consistent with applicable laws and Manulife/John Hancock policies. To request a reasonable accommodation in the application process, contact recruitment@manulife.com.<!----><span><br></span><span><br></span><span><strong><!---->Working Arrangement<!----><span><br></span><span><br></span></strong></span><!---->Hybrid<!---->
  </p>`,
    location: "NewYork, USA",
    company_logo:
      "https://cdn-dynamic.talent.com/ajax/img/get-logo.php?empcode=manulife&empname=Manulife&v=024",
  },
  {
    title: "Customer Service Analyst 3",
    slug: "customer-service-analyst-3",
    short_desc:
      "Job Description The opportunityThis role is accountable for providing quality, phone based customer service to callers. Requires advanced knowledge of products and processes to res...",
    company: "Manulife",
    long_desc: `<p dir="ltr">
    <!---->The opportunity<!----><span><br></span><span><br></span><!---->We are looking for Project Manager who is able to manages, coordinates business and technical projects through all phases of professional project manager: initiation, Planning, Executing, Monitor &amp; Control and Close. You shall work with dynamic, professional, and strong core values organization.<!----><span><br></span><span><br></span><span><strong><!---->Responsibilities<!----><span><br></span><span><br></span></strong></span><span>      <ul><span><li><!---->Responsible for Planning, Executing, Monitor &amp; Control and Close technical and business projects across multiple stakeholders; developing analysis to support process and project improvements.<!----></li></span><span><li><!---->Manages and coordinates business and technical projects through all phases of initiation, development, and implementation; tends to work on waterfall projects<!----></li></span><span><li><!---->Works with business to define and manage the scope, strategy, requirements, and implementation of projects<!----></li></span><span><li><!---->Ensures that assigned projects are completed within budgets and schedules while meeting business objectives<!----></li></span><span><li><!---->Identifies, analyzes, mitigates, documents, and controls project risks<!----></li></span><span><li><!---->Provides effective and regular communication within the project team, stakeholders, sponsors, and management<!----></li></span><span><li><!---->Identifies resource needs for the project and establishes roles, expectations, and goals with team members<!----></li></span><span><li><!---->Assess and manages risks that impede successful project delivery<!----></li></span><span><li><!---->Has positive impact to specific organizational entities &amp; has some understanding of the nature of the impact<!----></li></span><span><li><!---->Participates in negotiation of contract terms and conditions and ensure compliance with contract terms for project consultants and vendors<!----></li></span><span><li><!---->Responsible for assisting in hiring project staff, and developing motivating, coaching, advising, and managing the project team<!----></li></span><span><li><!---->Manage the technical components of the project or act as manager of personnel, including evaluating personnel<!----><span><br></span><span><br></span></li></span></ul>
</span><span><strong><!---->How will you create impact?<!----><span><br></span><span><br></span></strong></span><!---->This role report to Head of IT Delivery. You are IT delivery manager to delivery technology roadmap of organization to business. Working very closely with Business to understand demand and consult, drive them for digital transformation<!----><span><br></span><span><br></span><span><strong><!---->What motivates you?<!----><span><br></span><span><br></span></strong></span><span>      <ul><span><li><!---->You obsess about customers, listen, engage, and act for their benefit.<!----></li></span><span><li><!---->You think big, with curiosity to discover ways to use your agile approach and enable business outcomes.<!----></li></span><span><li><!---->You thrive in teams and enjoy getting things done together.<!----></li></span><span><li><!---->You take ownership and build solutions, focusing on what matters.<!----></li></span><span><li><!---->You do what is right, work with integrity and speak up.<!----></li></span><span><li><!---->You share your humanity, helping us build a diverse and inclusive work environment for everyone.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->What we are looking for<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->Proven Experienced and strong project management experience using waterfall and agile.<!----></li></span><span><li><!---->Well planning, execute, Monitor and control project scope, budget, time.<!----></li></span><span><li><!---->Excellent stakeholder’s management and communication<!----></li></span><span><li><!---->Life insurance industry experience is plus<!----></li></span><span><li><!---->Experience working with distributed teams across locations.<!----></li></span><span><li><!---->Good at communication skills, both in English and Vietnamese<!----></li></span><span><li><!---->Good problem solving<!----></li></span><span><li><!---->Certified PMI-PMP is preferable.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->What can we offer you?<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->A competitive salary and benefits packages.<!----></li></span><span><li><!---->A growth trajectory that extends upward and outward, encouraging you to follow your passions and learn new skills.<!----></li></span><span><li><!---->A focus on growing your career path with us.<!----></li></span><span><li><!---->Flexible work policies and strong work-life balance.<!----></li></span><span><li><!---->Professional development and leadership opportunities.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->Our commitment to you<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->Values-first culture: We lead with our Values every day and bring them to life together.<!----></li></span><span><li><!---->Boundless opportunity: We create opportunities to learn and grow at every stage of your career.<!----></li></span><span><li><!---->Continuous innovation: We invite you to help redefine the future of financial services.<!----></li></span><span><li><!---->Delivering the promise of Diversity, Equity and Inclusion: We foster an inclusive workplace where everyone thrives.<!----></li></span><span><li><!---->Championing Corporate Citizenship: We build a business that benefits all stakeholders and has a positive social and environmental impact.<!----><span><br></span><span><br></span></li></span></ul>
</span><span><strong><!---->About Manulife And John Hancock<!----><span><br></span><span><br></span></strong></span><!---->Manulife Financial Corporation is a leading international financial services provider, helping people make their decisions easier and lives better. To learn more about us, visit<span class="white-space-pre"> </span><a class="app-aware-link " target="_blank" href="https://www.manulife.com/en/about/our-story.html" data-test-app-aware-link=""><!---->https://www.manulife.com/en/about/our-story.html<!----></a><!---->.<!----><span><br></span><span><br></span><span><strong><!---->Manulife is an Equal Opportunity Employer<!----><span><br></span><span><br></span></strong></span><!---->At Manulife/John Hancock, we embrace our diversity. We strive to attract, develop and retain a workforce that is as diverse as the customers we serve and to foster an inclusive work environment that embraces the strength of cultures and individuals. We are committed to fair recruitment, retention, advancement and compensation, and we administer all of our practices and programs without discrimination on the basis of race, ancestry, place of origin, colour, ethnic origin, citizenship, religion or religious beliefs, creed, sex (including pregnancy and pregnancy-related conditions), sexual orientation, genetic characteristics, veteran status, gender identity, gender expression, age, marital status, family status, disability, or any other ground protected by applicable law.<!----><span><br></span><span><br></span><!---->It is our priority to remove barriers to provide equal access to employment. A Human Resources representative will work with applicants who request a reasonable accommodation during the application process. All information shared during the accommodation request process will be stored and used in a manner that is consistent with applicable laws and Manulife/John Hancock policies. To request a reasonable accommodation in the application process, contact recruitment@manulife.com.<!----><span><br></span><span><br></span><span><strong><!---->Working Arrangement<!----><span><br></span><span><br></span></strong></span><!---->Hybrid<!---->
  </p>`,
    salary: "700$",

    location: "NewYork, USA",
    company_logo:
      "https://cdn-dynamic.talent.com/ajax/img/get-logo.php?empcode=manulife&empname=Manulife&v=024",
  },
  {
    title: "Customer Service Analyst 4",
    slug: "customer-service-analyst-4",
    long_desc: `<p dir="ltr">
    <!---->The opportunity<!----><span><br></span><span><br></span><!---->We are looking for Project Manager who is able to manages, coordinates business and technical projects through all phases of professional project manager: initiation, Planning, Executing, Monitor &amp; Control and Close. You shall work with dynamic, professional, and strong core values organization.<!----><span><br></span><span><br></span><span><strong><!---->Responsibilities<!----><span><br></span><span><br></span></strong></span><span>      <ul><span><li><!---->Responsible for Planning, Executing, Monitor &amp; Control and Close technical and business projects across multiple stakeholders; developing analysis to support process and project improvements.<!----></li></span><span><li><!---->Manages and coordinates business and technical projects through all phases of initiation, development, and implementation; tends to work on waterfall projects<!----></li></span><span><li><!---->Works with business to define and manage the scope, strategy, requirements, and implementation of projects<!----></li></span><span><li><!---->Ensures that assigned projects are completed within budgets and schedules while meeting business objectives<!----></li></span><span><li><!---->Identifies, analyzes, mitigates, documents, and controls project risks<!----></li></span><span><li><!---->Provides effective and regular communication within the project team, stakeholders, sponsors, and management<!----></li></span><span><li><!---->Identifies resource needs for the project and establishes roles, expectations, and goals with team members<!----></li></span><span><li><!---->Assess and manages risks that impede successful project delivery<!----></li></span><span><li><!---->Has positive impact to specific organizational entities &amp; has some understanding of the nature of the impact<!----></li></span><span><li><!---->Participates in negotiation of contract terms and conditions and ensure compliance with contract terms for project consultants and vendors<!----></li></span><span><li><!---->Responsible for assisting in hiring project staff, and developing motivating, coaching, advising, and managing the project team<!----></li></span><span><li><!---->Manage the technical components of the project or act as manager of personnel, including evaluating personnel<!----><span><br></span><span><br></span></li></span></ul>
</span><span><strong><!---->How will you create impact?<!----><span><br></span><span><br></span></strong></span><!---->This role report to Head of IT Delivery. You are IT delivery manager to delivery technology roadmap of organization to business. Working very closely with Business to understand demand and consult, drive them for digital transformation<!----><span><br></span><span><br></span><span><strong><!---->What motivates you?<!----><span><br></span><span><br></span></strong></span><span>      <ul><span><li><!---->You obsess about customers, listen, engage, and act for their benefit.<!----></li></span><span><li><!---->You think big, with curiosity to discover ways to use your agile approach and enable business outcomes.<!----></li></span><span><li><!---->You thrive in teams and enjoy getting things done together.<!----></li></span><span><li><!---->You take ownership and build solutions, focusing on what matters.<!----></li></span><span><li><!---->You do what is right, work with integrity and speak up.<!----></li></span><span><li><!---->You share your humanity, helping us build a diverse and inclusive work environment for everyone.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->What we are looking for<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->Proven Experienced and strong project management experience using waterfall and agile.<!----></li></span><span><li><!---->Well planning, execute, Monitor and control project scope, budget, time.<!----></li></span><span><li><!---->Excellent stakeholder’s management and communication<!----></li></span><span><li><!---->Life insurance industry experience is plus<!----></li></span><span><li><!---->Experience working with distributed teams across locations.<!----></li></span><span><li><!---->Good at communication skills, both in English and Vietnamese<!----></li></span><span><li><!---->Good problem solving<!----></li></span><span><li><!---->Certified PMI-PMP is preferable.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->What can we offer you?<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->A competitive salary and benefits packages.<!----></li></span><span><li><!---->A growth trajectory that extends upward and outward, encouraging you to follow your passions and learn new skills.<!----></li></span><span><li><!---->A focus on growing your career path with us.<!----></li></span><span><li><!---->Flexible work policies and strong work-life balance.<!----></li></span><span><li><!---->Professional development and leadership opportunities.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->Our commitment to you<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->Values-first culture: We lead with our Values every day and bring them to life together.<!----></li></span><span><li><!---->Boundless opportunity: We create opportunities to learn and grow at every stage of your career.<!----></li></span><span><li><!---->Continuous innovation: We invite you to help redefine the future of financial services.<!----></li></span><span><li><!---->Delivering the promise of Diversity, Equity and Inclusion: We foster an inclusive workplace where everyone thrives.<!----></li></span><span><li><!---->Championing Corporate Citizenship: We build a business that benefits all stakeholders and has a positive social and environmental impact.<!----><span><br></span><span><br></span></li></span></ul>
</span><span><strong><!---->About Manulife And John Hancock<!----><span><br></span><span><br></span></strong></span><!---->Manulife Financial Corporation is a leading international financial services provider, helping people make their decisions easier and lives better. To learn more about us, visit<span class="white-space-pre"> </span><a class="app-aware-link " target="_blank" href="https://www.manulife.com/en/about/our-story.html" data-test-app-aware-link=""><!---->https://www.manulife.com/en/about/our-story.html<!----></a><!---->.<!----><span><br></span><span><br></span><span><strong><!---->Manulife is an Equal Opportunity Employer<!----><span><br></span><span><br></span></strong></span><!---->At Manulife/John Hancock, we embrace our diversity. We strive to attract, develop and retain a workforce that is as diverse as the customers we serve and to foster an inclusive work environment that embraces the strength of cultures and individuals. We are committed to fair recruitment, retention, advancement and compensation, and we administer all of our practices and programs without discrimination on the basis of race, ancestry, place of origin, colour, ethnic origin, citizenship, religion or religious beliefs, creed, sex (including pregnancy and pregnancy-related conditions), sexual orientation, genetic characteristics, veteran status, gender identity, gender expression, age, marital status, family status, disability, or any other ground protected by applicable law.<!----><span><br></span><span><br></span><!---->It is our priority to remove barriers to provide equal access to employment. A Human Resources representative will work with applicants who request a reasonable accommodation during the application process. All information shared during the accommodation request process will be stored and used in a manner that is consistent with applicable laws and Manulife/John Hancock policies. To request a reasonable accommodation in the application process, contact recruitment@manulife.com.<!----><span><br></span><span><br></span><span><strong><!---->Working Arrangement<!----><span><br></span><span><br></span></strong></span><!---->Hybrid<!---->
  </p>`,
    short_desc:
      "Job Description The opportunityThis role is accountable for providing quality, phone based customer service to callers. Requires advanced knowledge of products and processes to res...",
    company: "Manulife",

    salary: "700$",

    location: "NewYork, USA",
    company_logo:
      "https://cdn-dynamic.talent.com/ajax/img/get-logo.php?empcode=manulife&empname=Manulife&v=024",
  },
  {
    title: "Customer Service Analyst 5",
    slug: "customer-service-analyst-5",
    long_desc: `<p dir="ltr">
    <!---->The opportunity<!----><span><br></span><span><br></span><!---->We are looking for Project Manager who is able to manages, coordinates business and technical projects through all phases of professional project manager: initiation, Planning, Executing, Monitor &amp; Control and Close. You shall work with dynamic, professional, and strong core values organization.<!----><span><br></span><span><br></span><span><strong><!---->Responsibilities<!----><span><br></span><span><br></span></strong></span><span>      <ul><span><li><!---->Responsible for Planning, Executing, Monitor &amp; Control and Close technical and business projects across multiple stakeholders; developing analysis to support process and project improvements.<!----></li></span><span><li><!---->Manages and coordinates business and technical projects through all phases of initiation, development, and implementation; tends to work on waterfall projects<!----></li></span><span><li><!---->Works with business to define and manage the scope, strategy, requirements, and implementation of projects<!----></li></span><span><li><!---->Ensures that assigned projects are completed within budgets and schedules while meeting business objectives<!----></li></span><span><li><!---->Identifies, analyzes, mitigates, documents, and controls project risks<!----></li></span><span><li><!---->Provides effective and regular communication within the project team, stakeholders, sponsors, and management<!----></li></span><span><li><!---->Identifies resource needs for the project and establishes roles, expectations, and goals with team members<!----></li></span><span><li><!---->Assess and manages risks that impede successful project delivery<!----></li></span><span><li><!---->Has positive impact to specific organizational entities &amp; has some understanding of the nature of the impact<!----></li></span><span><li><!---->Participates in negotiation of contract terms and conditions and ensure compliance with contract terms for project consultants and vendors<!----></li></span><span><li><!---->Responsible for assisting in hiring project staff, and developing motivating, coaching, advising, and managing the project team<!----></li></span><span><li><!---->Manage the technical components of the project or act as manager of personnel, including evaluating personnel<!----><span><br></span><span><br></span></li></span></ul>
</span><span><strong><!---->How will you create impact?<!----><span><br></span><span><br></span></strong></span><!---->This role report to Head of IT Delivery. You are IT delivery manager to delivery technology roadmap of organization to business. Working very closely with Business to understand demand and consult, drive them for digital transformation<!----><span><br></span><span><br></span><span><strong><!---->What motivates you?<!----><span><br></span><span><br></span></strong></span><span>      <ul><span><li><!---->You obsess about customers, listen, engage, and act for their benefit.<!----></li></span><span><li><!---->You think big, with curiosity to discover ways to use your agile approach and enable business outcomes.<!----></li></span><span><li><!---->You thrive in teams and enjoy getting things done together.<!----></li></span><span><li><!---->You take ownership and build solutions, focusing on what matters.<!----></li></span><span><li><!---->You do what is right, work with integrity and speak up.<!----></li></span><span><li><!---->You share your humanity, helping us build a diverse and inclusive work environment for everyone.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->What we are looking for<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->Proven Experienced and strong project management experience using waterfall and agile.<!----></li></span><span><li><!---->Well planning, execute, Monitor and control project scope, budget, time.<!----></li></span><span><li><!---->Excellent stakeholder’s management and communication<!----></li></span><span><li><!---->Life insurance industry experience is plus<!----></li></span><span><li><!---->Experience working with distributed teams across locations.<!----></li></span><span><li><!---->Good at communication skills, both in English and Vietnamese<!----></li></span><span><li><!---->Good problem solving<!----></li></span><span><li><!---->Certified PMI-PMP is preferable.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->What can we offer you?<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->A competitive salary and benefits packages.<!----></li></span><span><li><!---->A growth trajectory that extends upward and outward, encouraging you to follow your passions and learn new skills.<!----></li></span><span><li><!---->A focus on growing your career path with us.<!----></li></span><span><li><!---->Flexible work policies and strong work-life balance.<!----></li></span><span><li><!---->Professional development and leadership opportunities.<!----><span><br></span><span><br></span></li></span></ul>
</span><!---->Our commitment to you<!----><span><br></span><span><br></span><span>      <ul><span><li><!---->Values-first culture: We lead with our Values every day and bring them to life together.<!----></li></span><span><li><!---->Boundless opportunity: We create opportunities to learn and grow at every stage of your career.<!----></li></span><span><li><!---->Continuous innovation: We invite you to help redefine the future of financial services.<!----></li></span><span><li><!---->Delivering the promise of Diversity, Equity and Inclusion: We foster an inclusive workplace where everyone thrives.<!----></li></span><span><li><!---->Championing Corporate Citizenship: We build a business that benefits all stakeholders and has a positive social and environmental impact.<!----><span><br></span><span><br></span></li></span></ul>
</span><span><strong><!---->About Manulife And John Hancock<!----><span><br></span><span><br></span></strong></span><!---->Manulife Financial Corporation is a leading international financial services provider, helping people make their decisions easier and lives better. To learn more about us, visit<span class="white-space-pre"> </span><a class="app-aware-link " target="_blank" href="https://www.manulife.com/en/about/our-story.html" data-test-app-aware-link=""><!---->https://www.manulife.com/en/about/our-story.html<!----></a><!---->.<!----><span><br></span><span><br></span><span><strong><!---->Manulife is an Equal Opportunity Employer<!----><span><br></span><span><br></span></strong></span><!---->At Manulife/John Hancock, we embrace our diversity. We strive to attract, develop and retain a workforce that is as diverse as the customers we serve and to foster an inclusive work environment that embraces the strength of cultures and individuals. We are committed to fair recruitment, retention, advancement and compensation, and we administer all of our practices and programs without discrimination on the basis of race, ancestry, place of origin, colour, ethnic origin, citizenship, religion or religious beliefs, creed, sex (including pregnancy and pregnancy-related conditions), sexual orientation, genetic characteristics, veteran status, gender identity, gender expression, age, marital status, family status, disability, or any other ground protected by applicable law.<!----><span><br></span><span><br></span><!---->It is our priority to remove barriers to provide equal access to employment. A Human Resources representative will work with applicants who request a reasonable accommodation during the application process. All information shared during the accommodation request process will be stored and used in a manner that is consistent with applicable laws and Manulife/John Hancock policies. To request a reasonable accommodation in the application process, contact recruitment@manulife.com.<!----><span><br></span><span><br></span><span><strong><!---->Working Arrangement<!----><span><br></span><span><br></span></strong></span><!---->Hybrid<!---->
  </p>`,
    short_desc:
      "Job Description The opportunityThis role is accountable for providing quality, phone based customer service to callers. Requires advanced knowledge of products and processes to res...",
    company: "Manulife",
    salary: "700$",
    location: "NewYork, USA",
    company_logo:
      "https://cdn-dynamic.talent.com/ajax/img/get-logo.php?empcode=manulife&empname=Manulife&v=024",
  },
];


